// facts.js
const facts = [
    "Human cuts 475 trees per second.",
    "Up to 30% of distributed water is lost due to leakage.",
    "Around 15 billion trees are removed annually.",
    "18 million acres of forests are lost each year.",
    "Deforestation accounts for nearly 10% of global carbon emissions.",
    "The amazon has lost about 17% of its cover in the past 50 years.",
    "Over 1 million species are at risk of extinction due to habitat loss.",
    "Illegal logging makes up to 50% of the global timber trade.",
    "Urban expansion has reduced natural habitats by over 40% in some regions.",
    "Around 1.2 billion people rely on forests for their livelihoods.",
    "Global agriculture uses about 70% of the world's freshwater.",
    "Up to 50% of agricultural water is lost due to evaporation and inefficient irrigation.",
    "Approximately 40% of the earth's land is used for agriculture.",
    "Around 1.3 billion tons of food are wasted every year.",
    "Food waste contributes nearly 8% of global greenhouse gas emissions.",
    "Single-use plastics can take up to 500 years to decompose.",
    "More than 8 million tons of plastic enter the oceans each year.",
    "Over 90% of seabirds have ingested plastic.",
    "Electronic waste is growing at about 3-4% per year globally.",
    "The world generated 53.6 million metric tons of e-waste in 2019.",
    "Recycling aluminum saves up to 95% of energy compared to new production.",
    "Renewable energy provided 29% of global electricity in 2020.",
    "Solar energy in one hour can meet the world's annual energy demand.",
    "A single wind turbine can power up to 300 homes.",
    "Hydropower accounts for about 16% of global electricity.",
    "Approximately 26% of global energy consumption is from renewable sources.",
    "Fossil fuels supplied 84% of global primary energy in 2019.",
    "Global co₂ levels have surpassed 415 parts per million.",
    "The last 7 years have been the hottest on record.",
    "Sea levels have risen by about 8 inches since 1880.",
    "Less than 1% of the earth's water is freshwater.",
    "Over 2 billion people lack access to safe drinking water.",
    "Water scarcity affects more than 40% of the global population.",
    "Urban areas can be up to 10°c warmer than rural surroundings.",
    "About 50% of electricity is lost during transmission.",
    "One-third of all food produced is never eaten.",
    "Over 30% of coral reefs have disappeared in the last 50 years.",
    "Ocean acidification has increased by 30% since the industrial revolution.",
    "Some fish stocks have dropped to less than 10% of their historical levels.",
    "The global wildlife trade is worth approximately $20 billion annually.",
    "Over 75% of the world's terrestrial ecosystems are in decline.",
    "Around 1.6 billion people live in areas vulnerable to natural disasters.",
    "Urban air pollution kills an estimated 7 million people per year.",
    "Indoor air pollution causes about 4 million premature deaths annually.",
    "The average energy efficiency of buildings is only around 50%.",
    "Nearly 50% of energy is lost in production and transmission.",
    "Indonesia has lost over 50% of its forests in the past 20 years.",
    "Over 60% of the world's wetlands have disappeared since 1900.",
    "Globally, 20% of all food produced is lost post-harvest.",
    "Current carbon capture technologies capture less than 0.1% of global co₂ emissions.",
    
    "Global agriculture emits over 8 billion metric tons of co₂ annually.",
    "More than 300,000 tons of oil spill into the oceans each year.",
    "80% of marine debris is plastic.",
    "A 1°c rise in global temperature could reduce crop yields by up to 25%.",
    "The world's population is projected to reach 9.7 billion by 2050.",
    "Fossil fuel subsidies exceed $5 trillion worldwide each year.",
    "Around 14% of energy is lost due to transmission inefficiencies.",
    "The energy return on investment for oil has fallen by nearly 50% over recent decades.",
    "Solar panel manufacturing accounts for approximately 10% of global emissions.",
    "Modern wind turbines have a lifespan of about 20-25 years.",
    "35% of the world's rivers are considered heavily polluted.",
    "1.8 billion people still rely on traditional biomass for cooking.",
    "Air pollution costs the global economy around 4.6% of gdp.",
    "Global agricultural land has expanded by 15% in the past 50 years.",
    "Agriculture accounts for approximately 22% of global greenhouse gas emissions.",
    "Industrial livestock production contributes 14.5% of global emissions.",
    "Livestock uses around 70% of all agricultural land.",
    "30% of global energy is used in food production processes.",
    "Dams alter the natural flow of 60% of the world's rivers.",
    "Tropical rainforests contain 70% of the world's biodiversity.",
    "Microplastics are present in 100% of the world's water bodies.",
    "Over 90% of seabed plastics consist of fibers.",
    "Ocean plastic pollution is projected to increase 2.5 times by 2025.",
    "90% of the world's coral reefs are at risk due to climate change and pollution.",
    "Urban tree canopy in major cities has declined by 30% over the last 20 years.",
    "More than 70% of the world's energy is still derived from fossil fuels.",
    "Hydroelectricity offers potential for a 20% growth in global electricity supply.",
    "Offshore wind energy could meet up to 18% of global electricity needs by 2050.",
    "Cement production contributes about 8% of global co₂ emissions.",
    "40% of all food produced is lost or wasted, costing nearly $940 billion.",
    "50% of global emissions are generated by just 10 countries.",
    "Human activities have altered nearly 30% of the earth's surface.",
    "Mining operations disturb approximately 12% of the earth's land surface.",
    "Beef production has a water footprint of around 15,000 liters per kilogram.",
    "High-income countries average a carbon footprint exceeding 10 tons per person per year.",
    "Global transport emissions are rising at a rate of about 2% per year.",
    "World energy demand is expected to increase by 50% by 2050.",
    "Approximately 30% of global fish stocks are currently overexploited.",
    "A single-use plastic bag can take up to 1,000 years to degrade.",
    "Renewable energy currently makes up less than 20% of the global energy mix.",
    "Fossil fuel combustion releases nearly 36 billion tons of co₂ each year.",
    "The area affected by mining is about the size of england.",
    "20% of household energy is wasted due to inefficient appliances.",
    "80% of commercial fishing stocks are fully or overexploited.",
    "Cattle ranching drives over 60% of tropical deforestation.",
    "1 in 3 people experiences severe water stress at least one month per year.",
    "Plastic production accounts for approximately 8% of global emissions.",
    "Energy-efficient buildings can reduce energy use by up to 50%.",
    "Global solar energy potential exceeds current energy demand by over 100 times.",
    "The pace of urbanization is expected to create an additional 2.5 billion urban residents by 2050."
  ];
  
  export default facts;
  